"""added seats

Revision ID: 028106a7cb8a
Revises: fd847801fc78
Create Date: 2024-08-15 22:40:33.860395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028106a7cb8a'
down_revision = 'fd847801fc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_seats_bus_id_buses')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
