"""DONE

Revision ID: 097ca610c2ca
Revises: 7935e392baff
Create Date: 2024-08-16 09:54:13.684511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097ca610c2ca'
down_revision = '7935e392baff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buses_driver_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_buses_driver_id_drivers'), 'drivers', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_buses_driver_id_drivers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_buses_driver_id_users', 'users', ['driver_id'], ['id'])

    # ### end Alembic commands ###
