"""updated tables 

Revision ID: 0fef16b97eac
Revises: 95abbd0c6399
Create Date: 2024-08-08 21:48:40.820335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fef16b97eac'
down_revision = '95abbd0c6399'
branch_labels = None
depends_on = None


def upgrade():
    # Drop existing table if it exists (Warning: This will remove all data in the table)
    op.drop_table('contactus')
    
    # Then create the table again
    op.create_table('contactus',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # Other table creation commands...


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_routes')
    op.drop_table('bookings')
    op.drop_table('buses')
    op.drop_table('users')
    op.drop_table('routes')
    op.drop_table('reviews')
    op.drop_table('contactus')
    # ### end Alembic commands ###
