"""updated

Revision ID: 6881e01cefc2
Revises: 0c74a51a593f
Create Date: 2024-08-16 03:25:07.814157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6881e01cefc2'
down_revision = '0c74a51a593f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('idNumber', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('fk_bookings_customer_id_users', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_bookings_customer_id_users', 'users', ['customer_id'], ['id'])
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('idNumber')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
