"""updated routes

Revision ID: 95abbd0c6399
Revises: 8041852a3cbb
Create Date: 2024-08-08 18:49:51.649638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95abbd0c6399'
down_revision = '8041852a3cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_from', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('departure_to', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('departure_to')
        batch_op.drop_column('departure_from')

    # ### end Alembic commands ###
