"""updated

Revision ID: fd847801fc78
Revises: 9f044eba0704
Create Date: 2024-08-14 10:12:11.610591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd847801fc78'
down_revision = '9f044eba0704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('departure_from', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('departure_to', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_buses_driver_id_drivers'), 'drivers', ['driver_id'], ['id'])
        batch_op.drop_column('depatrture_from')
        batch_op.drop_column('depatrture_to')
        batch_op.drop_column('driver_full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_full_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('depatrture_to', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('depatrture_from', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_buses_driver_id_drivers'), type_='foreignkey')
        batch_op.drop_column('departure_to')
        batch_op.drop_column('departure_from')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
